/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author Mostafa
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Background = new javax.swing.JPanel();
        AdminHomeTitle = new javax.swing.JLabel();
        GenerateReportButton = new javax.swing.JButton();
        ManageClientsButton = new javax.swing.JButton();
        ManageMedicinesButton = new javax.swing.JButton();
        ManageDoctorsButton = new javax.swing.JButton();
        ManageAdminsButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));

        Background.setBackground(new java.awt.Color(37, 95, 214));
        Background.setForeground(new java.awt.Color(102, 102, 255));
        Background.setMinimumSize(new java.awt.Dimension(950, 600));
        Background.setPreferredSize(new java.awt.Dimension(950, 600));
        Background.setLayout(new java.awt.GridBagLayout());

        AdminHomeTitle.setBackground(new java.awt.Color(255, 255, 255));
        AdminHomeTitle.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        AdminHomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        AdminHomeTitle.setText("Admin Home");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(123, 124, 0, 0);
        Background.add(AdminHomeTitle, gridBagConstraints);

        GenerateReportButton.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        GenerateReportButton.setForeground(new java.awt.Color(37, 95, 214));
        GenerateReportButton.setText("Generate Report");
        GenerateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 291, 46);
        Background.add(GenerateReportButton, gridBagConstraints);

        ManageClientsButton.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        ManageClientsButton.setForeground(new java.awt.Color(37, 95, 214));
        ManageClientsButton.setText("Manage Clients");
        ManageClientsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageClientsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 291, 0);
        Background.add(ManageClientsButton, gridBagConstraints);

        ManageMedicinesButton.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        ManageMedicinesButton.setForeground(new java.awt.Color(37, 95, 214));
        ManageMedicinesButton.setText("Manage Medicines");
        ManageMedicinesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMedicinesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 291, 0);
        Background.add(ManageMedicinesButton, gridBagConstraints);

        ManageDoctorsButton.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        ManageDoctorsButton.setForeground(new java.awt.Color(37, 95, 214));
        ManageDoctorsButton.setText("Manage Doctors");
        ManageDoctorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDoctorsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 291, 0);
        Background.add(ManageDoctorsButton, gridBagConstraints);

        ManageAdminsButton1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        ManageAdminsButton1.setForeground(new java.awt.Color(37, 95, 214));
        ManageAdminsButton1.setText("Manage Admins");
        ManageAdminsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAdminsButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 80, 291, 0);
        Background.add(ManageAdminsButton1, gridBagConstraints);

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(966, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportButtonActionPerformed
        GenerateRportGUI next = new GenerateRportGUI();
        next.setSize(getSize());
        next.setLocation(getLocation());
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_GenerateReportButtonActionPerformed

    private void ManageClientsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageClientsButtonActionPerformed
        new ManageClients().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageClientsButtonActionPerformed

    private void ManageDoctorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDoctorsButtonActionPerformed
        new ManageDoctors().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageDoctorsButtonActionPerformed

    private void ManageMedicinesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMedicinesButtonActionPerformed
        new ManageMedicines().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageMedicinesButtonActionPerformed

    private void ManageAdminsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAdminsButton1ActionPerformed
        new ManageAdmins().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageAdminsButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminHomeTitle;
    private javax.swing.JPanel Background;
    private javax.swing.JButton GenerateReportButton;
    private javax.swing.JButton ManageAdminsButton1;
    private javax.swing.JButton ManageClientsButton;
    private javax.swing.JButton ManageDoctorsButton;
    private javax.swing.JButton ManageMedicinesButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
