/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class ManageClients extends javax.swing.JFrame {

    /**
     * Creates new form ManageClients
     */
    public ManageClients() {
        initComponents();
        
        //Set up placeholders for all text fields
        setupPlaceholder(ClientID, "Enter client ID");
        setupPlaceholder(ClientName, "Enter full name");
        setupPlaceholder(ClientUsername, "Enter username");
        setupPlaceholder(ClientEmail, "Enter email");
        setupPlaceholder(ClientPhone, "Enter phone number");
        setupPlaceholder(ClientAddress, "Enter address");
        setupPasswordPlaceholder(ClientPassword, "Enter password");
        
        // Window size + its place 
        this.setSize(950, 630);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.NORMAL);
        
        refreshTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Background = new javax.swing.JPanel();
        ManageClientsTitle = new javax.swing.JLabel();
        DeleteClient = new javax.swing.JButton();
        AddClient = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ClientID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ClientPhone = new javax.swing.JTextField();
        ClientName = new javax.swing.JTextField();
        ClientUsername = new javax.swing.JTextField();
        ClientEmail = new javax.swing.JTextField();
        ClientAddress = new javax.swing.JTextField();
        ClientPassword = new javax.swing.JPasswordField();
        ClientShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));

        Background.setBackground(new java.awt.Color(37, 95, 214));
        Background.setForeground(new java.awt.Color(102, 102, 255));
        Background.setMinimumSize(new java.awt.Dimension(950, 600));
        Background.setPreferredSize(new java.awt.Dimension(950, 600));
        Background.setLayout(new java.awt.GridBagLayout());

        ManageClientsTitle.setBackground(new java.awt.Color(255, 255, 255));
        ManageClientsTitle.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        ManageClientsTitle.setForeground(new java.awt.Color(255, 255, 255));
        ManageClientsTitle.setText("Manage Clients");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 68, 0, 0);
        Background.add(ManageClientsTitle, gridBagConstraints);

        DeleteClient.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        DeleteClient.setForeground(new java.awt.Color(37, 95, 214));
        DeleteClient.setText("Delete Client");
        DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 1, 35, 0);
        Background.add(DeleteClient, gridBagConstraints);

        AddClient.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        AddClient.setForeground(new java.awt.Color(37, 95, 214));
        AddClient.setText("Add Client");
        AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 84, 35, 0);
        Background.add(AddClient, gridBagConstraints);

        BackButton.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(37, 95, 214));
        BackButton.setText("<-");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 84, 0, 0);
        Background.add(BackButton, gridBagConstraints);

        ClientID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientID.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientID.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 154, 0, 0);
        Background.add(ClientID, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Email", "Phone", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 440;
        gridBagConstraints.ipady = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(19, 32, 35, 34);
        Background.add(jScrollPane1, gridBagConstraints);

        ClientPhone.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientPhone.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientPhone.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientPhoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientPhone, gridBagConstraints);

        ClientName.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientName.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientName.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientName, gridBagConstraints);

        ClientUsername.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientUsername.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientUsername.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientUsername, gridBagConstraints);

        ClientEmail.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientEmail.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientEmail.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientEmail, gridBagConstraints);

        ClientAddress.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientAddress.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientAddress.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientAddressActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientAddress, gridBagConstraints);

        ClientPassword.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        ClientPassword.setMinimumSize(new java.awt.Dimension(100, 30));
        ClientPassword.setPreferredSize(new java.awt.Dimension(100, 30));
        ClientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientPassword, gridBagConstraints);

        ClientShowPassword.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        ClientShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ClientShowPassword.setText("Show Password");
        ClientShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientShowPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 154, 0, 0);
        Background.add(ClientShowPassword, gridBagConstraints);

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a client to delete.");
            return;
        }

        String clientId = jTable1.getValueAt(selectedRow, 0).toString();

        Client toDelete = null;
        for (Client client : Client.getClients()) 
        {
            if (client.getId().equals(clientId)) 
            {
                toDelete = client;
                break;
            }
        }

        if (toDelete != null) 
        {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this client?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) 
            {
                Client.getClients().remove(toDelete);
                refreshTable();
                javax.swing.JOptionPane.showMessageDialog(this, "Client deleted successfully!");
            }
        } 
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected client not found.");
        }
    }//GEN-LAST:event_DeleteClientActionPerformed

    private void AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientActionPerformed
        String id = ClientID.getText().trim();
        String name = ClientName.getText().trim();
        String username = ClientUsername.getText().trim();
        String email = ClientEmail.getText().trim();
        String phone = ClientPhone.getText().trim();
        String address = ClientAddress.getText().trim();
        String password = ClientPassword.getText().trim();

        // Validation
        if (id.isEmpty() || name.isEmpty() || username.isEmpty() || email.isEmpty() || phone.isEmpty() || address.isEmpty() || password.isEmpty()) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format.");
            return;
        }

        if (!phone.matches("\\d+")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number must contain digits only.");
            return;
        }

        // Check if username already exists
        for (Client client : Client.getClients()) 
        {
            if (client.getUsername().equals(username)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Username already exists. Please choose another.");
                return;
            }
        }

        // Create a new client and add it to the list
        Client newClient = new Client(id, name, username, email, phone, password, address);
        Client.addClient(newClient);

        refreshTable();
        clearFields();

        javax.swing.JOptionPane.showMessageDialog(this, "Client added successfully!");
    }//GEN-LAST:event_AddClientActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new AdminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ClientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientPhoneActionPerformed

    private void ClientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientIDActionPerformed

    private void ClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientNameActionPerformed

    private void ClientUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientUsernameActionPerformed

    private void ClientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientEmailActionPerformed

    private void ClientAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientAddressActionPerformed

    private void ClientShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientShowPasswordActionPerformed
        if (String.valueOf(ClientPassword.getPassword()).equals("Enter password")) {
            return; // If it is the password placeholder, return and change nothing.
        }

        if (ClientShowPassword.isSelected())
        {
            ClientPassword.setEchoChar((char)0);
        }
        else
        {
            ClientPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ClientShowPasswordActionPerformed

    private void ClientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientPasswordActionPerformed
    
    private void clearFields() 
    {
        ClientID.setForeground(Color.GRAY);
        ClientID.setText("Enter client ID");

        ClientName.setForeground(Color.GRAY);
        ClientName.setText("Enter full name");

        ClientUsername.setForeground(Color.GRAY);
        ClientUsername.setText("Enter username");

        ClientEmail.setForeground(Color.GRAY);
        ClientEmail.setText("Enter email");

        ClientPhone.setForeground(Color.GRAY);
        ClientPhone.setText("Enter phone number");
        
        ClientAddress.setForeground(Color.GRAY);
        ClientAddress.setText("Enter address");

        ClientPassword.setForeground(Color.GRAY);
        ClientPassword.setEchoChar((char)0);
        ClientPassword.setText("Enter password");
}   

    private void refreshTable() 
    {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Client client : Client.getClients()) 
        {
            model.addRow(new Object[]{client.getId(), client.getName(), client.getUsername(), client.getEmail(), client.getPhone(), client.getAddress(), client.getPassword()});
        }
    }
    
    private void setupPlaceholder(JTextField textField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        textField.setForeground(Color.GRAY);
        textField.setFont(fontUsed);
        textField.setText(placeholder);

        textField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().equals(placeholder)) 
                {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                    textField.setFont(fontUsed);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().isEmpty()) 
                {
                    textField.setForeground(Color.GRAY);
                    textField.setFont(fontUsed);
                    textField.setText(placeholder);
                }
            }
        });
    }
    
    private void setupPasswordPlaceholder(JPasswordField passwordField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        passwordField.setForeground(Color.GRAY);
        passwordField.setFont(fontUsed);
        passwordField.setEchoChar((char)0); // Show actual text instead of '*'
        passwordField.setText(placeholder);

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (String.valueOf(passwordField.getPassword()).equals(placeholder)) 
                {
                    passwordField.setText("");
                    passwordField.setForeground(Color.BLACK);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar('*'); // Switch back to '*' when typing
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (passwordField.getPassword().length == 0) 
                {
                    passwordField.setForeground(Color.GRAY);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar((char)0); // Show actual text again
                    passwordField.setText(placeholder);
                }
            }
        }
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClient;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JTextField ClientAddress;
    private javax.swing.JTextField ClientEmail;
    private javax.swing.JTextField ClientID;
    private javax.swing.JTextField ClientName;
    private javax.swing.JPasswordField ClientPassword;
    private javax.swing.JTextField ClientPhone;
    private javax.swing.JCheckBox ClientShowPassword;
    private javax.swing.JTextField ClientUsername;
    private javax.swing.JButton DeleteClient;
    private javax.swing.JLabel ManageClientsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
