/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class ManageDoctors extends javax.swing.JFrame {

    /**
     * Creates new form ManageDoctors
     */
    public ManageDoctors() {
        initComponents();
        
        //Set up placeholders for all text fields
        setupPlaceholder(DoctorID, "Enter doctor ID");
        setupPlaceholder(DoctorName, "Enter full name");
        setupPlaceholder(DoctorUsername, "Enter username");
        setupPlaceholder(DoctorEmail, "Enter email");
        setupPlaceholder(DoctorPhone, "Enter phone number");
        setupPlaceholder(DoctorConsulstionFee, "Enter consulstion fee");
        setupPlaceholder(DoctorLicenseNumber, "Enter license number");
        setupPlaceholder(DoctorSpecialization, "Enter specialization");
        setupPasswordPlaceholder(DoctorPassword, "Enter password");
        
        // Window size + its place 
        this.setSize(950, 630);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.NORMAL);
        
        refreshTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Background = new javax.swing.JPanel();
        ManageDoctorsTitle = new javax.swing.JLabel();
        AddDoctor = new javax.swing.JButton();
        DeleteDoctor = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DoctorID = new javax.swing.JTextField();
        DoctorName = new javax.swing.JTextField();
        DoctorUsername = new javax.swing.JTextField();
        DoctorEmail = new javax.swing.JTextField();
        DoctorPhone = new javax.swing.JTextField();
        DoctorConsulstionFee = new javax.swing.JTextField();
        DoctorSpecialization = new javax.swing.JTextField();
        DoctorLicenseNumber = new javax.swing.JTextField();
        DoctorPassword = new javax.swing.JPasswordField();
        DoctorShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(37, 95, 214));
        Background.setForeground(new java.awt.Color(37, 95, 214));
        Background.setLayout(new java.awt.GridBagLayout());

        ManageDoctorsTitle.setBackground(new java.awt.Color(255, 255, 255));
        ManageDoctorsTitle.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        ManageDoctorsTitle.setForeground(new java.awt.Color(255, 255, 255));
        ManageDoctorsTitle.setText("Manage Doctors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 53, 0, 0);
        Background.add(ManageDoctorsTitle, gridBagConstraints);

        AddDoctor.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        AddDoctor.setForeground(new java.awt.Color(37, 95, 214));
        AddDoctor.setText("Add Doctor");
        AddDoctor.setMaximumSize(new java.awt.Dimension(127, 31));
        AddDoctor.setMinimumSize(new java.awt.Dimension(127, 31));
        AddDoctor.setPreferredSize(new java.awt.Dimension(127, 31));
        AddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 34, 56, 0);
        Background.add(AddDoctor, gridBagConstraints);

        DeleteDoctor.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        DeleteDoctor.setForeground(new java.awt.Color(37, 95, 214));
        DeleteDoctor.setText("Delete Doctor");
        DeleteDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDoctorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 56, 0);
        Background.add(DeleteDoctor, gridBagConstraints);

        BackButton.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(37, 95, 214));
        BackButton.setText("<-");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 34, 0, 0);
        Background.add(BackButton, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Email", "Phone", "Consultstion Fee", "License Number", "Specialization"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 768;
        gridBagConstraints.ipady = 433;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(60, 6, 56, 48);
        Background.add(jScrollPane1, gridBagConstraints);

        DoctorID.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorID.setMinimumSize(new java.awt.Dimension(100, 30));
        DoctorID.setPreferredSize(new java.awt.Dimension(100, 30));
        DoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(63, 6, 0, 0);
        Background.add(DoctorID, gridBagConstraints);

        DoctorName.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorName.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorName.setMinimumSize(new java.awt.Dimension(100, 30));
        DoctorName.setPreferredSize(new java.awt.Dimension(100, 30));
        DoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorName, gridBagConstraints);

        DoctorUsername.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorUsername.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorUsername.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorUsername.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorUsername, gridBagConstraints);

        DoctorEmail.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorEmail.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorEmail.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorEmail.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorEmail, gridBagConstraints);

        DoctorPhone.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorPhone.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorPhone.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorPhone.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorPhoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorPhone, gridBagConstraints);

        DoctorConsulstionFee.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorConsulstionFee.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorConsulstionFee.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorConsulstionFee.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorConsulstionFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorConsulstionFeeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorConsulstionFee, gridBagConstraints);

        DoctorSpecialization.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorSpecialization.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorSpecialization.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorSpecialization.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSpecializationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorSpecialization, gridBagConstraints);

        DoctorLicenseNumber.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorLicenseNumber.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorLicenseNumber.setMinimumSize(new java.awt.Dimension(200, 30));
        DoctorLicenseNumber.setPreferredSize(new java.awt.Dimension(200, 30));
        DoctorLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorLicenseNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorLicenseNumber, gridBagConstraints);

        DoctorPassword.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        DoctorPassword.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        DoctorPassword.setMinimumSize(new java.awt.Dimension(100, 30));
        DoctorPassword.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorPassword, gridBagConstraints);

        DoctorShowPassword.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        DoctorShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        DoctorShowPassword.setText("Show Password");
        DoctorShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorShowPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        Background.add(DoctorShowPassword, gridBagConstraints);

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorActionPerformed
        String id = DoctorID.getText().trim();
        String name = DoctorName.getText().trim();
        String username = DoctorUsername.getText().trim();
        String email = DoctorEmail.getText().trim();
        String phone = DoctorPhone.getText().trim();
        String specialization = DoctorSpecialization.getText().trim();
        String licenseNumber = DoctorLicenseNumber.getText().trim();
        String consultationFeeStr = DoctorConsulstionFee.getText().trim();
        String password = DoctorPassword.getText().trim(); 

        // Validate input
        if (id.isEmpty() || name.isEmpty() || username.isEmpty() || email.isEmpty() || phone.isEmpty() || specialization.isEmpty() || licenseNumber.isEmpty() || consultationFeeStr.isEmpty() || password.isEmpty()) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format.");
            return;
        }

        if (!phone.matches("\\d+")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number must contain digits only.");
            return;
        }

        float consultationFee;
        try 
        {
            consultationFee = Float.parseFloat(consultationFeeStr);
            if (consultationFee <= 0) 
            {
                throw new NumberFormatException();
            }
        } 
        catch (NumberFormatException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Consultation fee must be a positive number.");
            return;
        }

        // Check for duplicate username and license number
        for (Doctor doctor : Doctor.getDoctors()) 
        {
            if (doctor.getUsername().equals(username)) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Username already exists.");
                return;
            }
            if (doctor.getLicenseNumber().equals(licenseNumber)) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "License number already exists.");
                return;
            }
        }

    // Create and add new doctor
    Doctor newDoctor = new Doctor(specialization, licenseNumber, consultationFee, id, name, username, email, phone, password);
    Doctor.addDoctor(newDoctor);

    refreshTable();
    clearFields();
    javax.swing.JOptionPane.showMessageDialog(this, "Doctor added successfully!");
    }//GEN-LAST:event_AddDoctorActionPerformed

    private void DeleteDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDoctorActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a doctor to delete.");
            return;
        }

        String doctorId = jTable1.getValueAt(selectedRow, 0).toString();

        Doctor doctorToRemove = null;
        for (Doctor doctor : Doctor.getDoctors()) 
        {
            if (doctor.getId().equals(doctorId)) 
            {
                doctorToRemove = doctor;
                break;
            }
        }

        if (doctorToRemove != null) 
        {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this doctor?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

                if (confirm == javax.swing.JOptionPane.YES_OPTION) 
                {
                    Doctor.removeDoctor(doctorToRemove);
                    refreshTable();
                    javax.swing.JOptionPane.showMessageDialog(this, "Doctor deleted successfully!");
                }
        }
        else 
        {
                javax.swing.JOptionPane.showMessageDialog(this, "Selected doctor not found.");
        }
    }//GEN-LAST:event_DeleteDoctorActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new AdminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorIDActionPerformed

    private void DoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameActionPerformed

    private void DoctorUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorUsernameActionPerformed

    private void DoctorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorEmailActionPerformed

    private void DoctorPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorPhoneActionPerformed

    private void DoctorConsulstionFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorConsulstionFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorConsulstionFeeActionPerformed

    private void DoctorSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorSpecializationActionPerformed

    private void DoctorLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorLicenseNumberActionPerformed

    private void DoctorShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorShowPasswordActionPerformed
        if (String.valueOf(DoctorPassword.getPassword()).equals("Enter password")) {
            return; // If it is the password placeholder, return and change nothing.
        }

        if (DoctorShowPassword.isSelected())
        {
            DoctorPassword.setEchoChar((char)0);
        }
        else
        {
            DoctorPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_DoctorShowPasswordActionPerformed
    
    private void refreshTable() 
    {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Doctor doctor : Doctor.getDoctors()) {
            model.addRow(new Object[]{doctor.getId(), doctor.getName(), doctor.getUsername(), doctor.getEmail(), doctor.getPhone(), doctor.getConsultstionFee(), doctor.getLicenseNumber(), doctor.getSpecialization(), doctor.getPassword(),});
        }
    }
    
    private void clearFields() 
    {
        DoctorID.setForeground(Color.GRAY);
        DoctorID.setText("Enter doctor ID");

        DoctorName.setForeground(Color.GRAY);
        DoctorName.setText("Enter full name");

        DoctorUsername.setForeground(Color.GRAY);
        DoctorUsername.setText("Enter username");

        DoctorEmail.setForeground(Color.GRAY);
        DoctorEmail.setText("Enter email");

        DoctorPhone.setForeground(Color.GRAY);
        DoctorPhone.setText("Enter phone number");
        
        DoctorSpecialization.setForeground(Color.GRAY);
        DoctorSpecialization.setText("Enter specialization");

        DoctorLicenseNumber.setForeground(Color.GRAY);
        DoctorLicenseNumber.setText("Enter license number");

        DoctorConsulstionFee.setForeground(Color.GRAY);
        DoctorConsulstionFee.setText("Enter consulstion fee");
        
        DoctorPassword.setForeground(Color.GRAY);
        DoctorPassword.setEchoChar((char)0);
        DoctorPassword.setText("Enter password");
    }
    
    private void setupPlaceholder(JTextField textField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        textField.setForeground(Color.GRAY);
        textField.setFont(fontUsed);
        textField.setText(placeholder);

        textField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().equals(placeholder)) 
                {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                    textField.setFont(fontUsed);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().isEmpty()) 
                {
                    textField.setForeground(Color.GRAY);
                    textField.setFont(fontUsed);
                    textField.setText(placeholder);
                }
            }
        });
    }
    
    private void setupPasswordPlaceholder(JPasswordField passwordField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        passwordField.setForeground(Color.GRAY);
        passwordField.setFont(fontUsed);
        passwordField.setEchoChar((char)0); // Show actual text instead of '*'
        passwordField.setText(placeholder);

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (String.valueOf(passwordField.getPassword()).equals(placeholder)) 
                {
                    passwordField.setText("");
                    passwordField.setForeground(Color.BLACK);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar('*'); // Switch back to '*' when typing
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (passwordField.getPassword().length == 0) 
                {
                    passwordField.setForeground(Color.GRAY);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar((char)0); // Show actual text again
                    passwordField.setText(placeholder);
                }
            }
        }
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDoctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctor;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JButton DeleteDoctor;
    private javax.swing.JTextField DoctorConsulstionFee;
    private javax.swing.JTextField DoctorEmail;
    private javax.swing.JTextField DoctorID;
    private javax.swing.JTextField DoctorLicenseNumber;
    private javax.swing.JTextField DoctorName;
    private javax.swing.JPasswordField DoctorPassword;
    private javax.swing.JTextField DoctorPhone;
    private javax.swing.JCheckBox DoctorShowPassword;
    private javax.swing.JTextField DoctorSpecialization;
    private javax.swing.JTextField DoctorUsername;
    private javax.swing.JLabel ManageDoctorsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
