/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import javaapplication2.Medicine;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class ManageMedicines extends javax.swing.JFrame {

    /**
     * Creates new form ManageMedicines
     */
    public ManageMedicines() {
        initComponents();
        
        //Set up placeholders for all text fields
        setupPlaceholder(MedicineID, "Enter medicine ID");
        setupPlaceholder(MedicineName, "Enter name");
        setupPlaceholder(MedicineBatchNumber, "Enter batch number");
        setupPlaceholder(MedicinePrice, "Enter price");
        setupPlaceholder(MedicineQuantity, "Enter quantity");
        setupPlaceholder(MedicineExpiryDate, "Enter expiry date (YYYY-MM-DD)");
        
        // Window size + its place 
        this.setSize(950, 630);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.NORMAL);
        
        refreshTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Background = new javax.swing.JPanel();
        ManageMedicinesTitle = new javax.swing.JLabel();
        AddMedicine = new javax.swing.JButton();
        UpdateMedicine = new javax.swing.JButton();
        DeleteMedicine = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MedicineQuantity = new javax.swing.JTextField();
        MedicineID = new javax.swing.JTextField();
        MedicineName = new javax.swing.JTextField();
        MedicineBatchNumber = new javax.swing.JTextField();
        MedicinePrice = new javax.swing.JTextField();
        MedicineExpiryDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(37, 95, 214));
        Background.setLayout(new java.awt.GridBagLayout());

        ManageMedicinesTitle.setBackground(new java.awt.Color(255, 255, 255));
        ManageMedicinesTitle.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        ManageMedicinesTitle.setForeground(new java.awt.Color(255, 255, 255));
        ManageMedicinesTitle.setText("Manage Medicines");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 24, 0, 0);
        Background.add(ManageMedicinesTitle, gridBagConstraints);

        AddMedicine.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        AddMedicine.setForeground(new java.awt.Color(37, 95, 214));
        AddMedicine.setText("Add Medicine");
        AddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedicineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 58, 0, 0);
        Background.add(AddMedicine, gridBagConstraints);

        UpdateMedicine.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        UpdateMedicine.setForeground(new java.awt.Color(37, 95, 214));
        UpdateMedicine.setText("Update Medicine");
        UpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedicineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 0);
        Background.add(UpdateMedicine, gridBagConstraints);

        DeleteMedicine.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        DeleteMedicine.setForeground(new java.awt.Color(37, 95, 214));
        DeleteMedicine.setText("Delete Medicine");
        DeleteMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMedicineActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 0);
        Background.add(DeleteMedicine, gridBagConstraints);

        BackButton.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        BackButton.setForeground(new java.awt.Color(37, 95, 214));
        BackButton.setText("<-");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 58, 0, 0);
        Background.add(BackButton, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Batch Number", "Price", "Quantity", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 434;
        gridBagConstraints.ipady = 380;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 25, 27);
        Background.add(jScrollPane1, gridBagConstraints);

        MedicineQuantity.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicineQuantity.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicineQuantity.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicineQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineQuantityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 58, 0, 0);
        Background.add(MedicineQuantity, gridBagConstraints);

        MedicineID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicineID.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicineID.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicineID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(76, 58, 0, 0);
        Background.add(MedicineID, gridBagConstraints);

        MedicineName.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicineName.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicineName.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicineName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 58, 0, 0);
        Background.add(MedicineName, gridBagConstraints);

        MedicineBatchNumber.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicineBatchNumber.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicineBatchNumber.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicineBatchNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineBatchNumberActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 58, 0, 0);
        Background.add(MedicineBatchNumber, gridBagConstraints);

        MedicinePrice.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicinePrice.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicinePrice.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicinePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicinePriceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 58, 0, 0);
        Background.add(MedicinePrice, gridBagConstraints);

        MedicineExpiryDate.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        MedicineExpiryDate.setMinimumSize(new java.awt.Dimension(516, 30));
        MedicineExpiryDate.setPreferredSize(new java.awt.Dimension(516, 30));
        MedicineExpiryDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineExpiryDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 58, 0, 0);
        Background.add(MedicineExpiryDate, gridBagConstraints);

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedicineActionPerformed
        String id = MedicineID.getText().trim();
        String name = MedicineName.getText().trim();
        String batchNo = MedicineBatchNumber.getText().trim();
        String priceStr = MedicinePrice.getText().trim();
        String quantityStr = MedicineQuantity.getText().trim();
        String expiryDate = MedicineExpiryDate.getText().trim();

        // Validate input
        if (id.isEmpty() || name.isEmpty() || batchNo.isEmpty() || priceStr.isEmpty() || quantityStr.isEmpty() || expiryDate.isEmpty()) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        // Validatation
        try 
        {
            int medicineId = Integer.parseInt(id);
            double price = Double.parseDouble(priceStr);
            int quantity = Integer.parseInt(quantityStr);

            if (price <= 0 || quantity <= 0) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Price and Quantity must be positive numbers.");
                return;
            }

            // Validate date format (simple validation)
            if (!expiryDate.matches("\\d{4}-\\d{2}-\\d{2}")) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.");
                return;
            }

            // Check if medicine with same ID already exists
            if (Medicine.findMedicineById(medicineId) != null) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Medicine with this ID already exists.");
                return;
            }

            // Create and add new medicine
            Date expiry = java.sql.Date.valueOf(expiryDate);
            Medicine newMedicine = new Medicine(medicineId, name, batchNo, price, quantity, expiry);
            Medicine.addMedicine(newMedicine);

            refreshTable();
            clearFields();
            javax.swing.JOptionPane.showMessageDialog(this, "Medicine added successfully!");

        } 
        catch (NumberFormatException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "ID, Price and Quantity must be valid numbers.");
        } 
        catch (IllegalArgumentException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.");
        }
    }//GEN-LAST:event_AddMedicineActionPerformed

    private void UpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedicineActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a medicine to update.");
            return;
        }

        String id = MedicineID.getText().trim();
        String name = MedicineName.getText().trim();
        String batchNo = MedicineBatchNumber.getText().trim();
        String priceStr = MedicinePrice.getText().trim();
        String quantityStr = MedicineQuantity.getText().trim();
        String expiryDate = MedicineExpiryDate.getText().trim();

        // Validate input
        if (id.isEmpty() || name.isEmpty() || batchNo.isEmpty() || priceStr.isEmpty() || quantityStr.isEmpty() || expiryDate.isEmpty()) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        try 
        {
            int medicineId = Integer.parseInt(id);
            double price = Double.parseDouble(priceStr);
            int quantity = Integer.parseInt(quantityStr);

            if (price <= 0 || quantity <= 0) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Price and Quantity must be positive numbers.");
                return;
            }

            // Validate date format
            if (!expiryDate.matches("\\d{4}-\\d{2}-\\d{2}")) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.");
                return;
            }

            // Create updated medicine
            Date expiry = java.sql.Date.valueOf(expiryDate);
            Medicine updatedMedicine = new Medicine(medicineId, name, batchNo, price, quantity, expiry);

            // Update the medicine
            boolean success = Medicine.updateMedicine(medicineId, updatedMedicine);

            if (success) 
            {
                refreshTable();
                clearFields();
                javax.swing.JOptionPane.showMessageDialog(this, "Medicine updated successfully!");
            }
            else 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to update medicine.");
            }

        }
        catch (NumberFormatException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "ID, Price and Quantity must be valid numbers.");
        }
        catch (IllegalArgumentException e) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid date format. Please use YYYY-MM-DD.");
        }
    }//GEN-LAST:event_UpdateMedicineActionPerformed

    private void DeleteMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMedicineActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a medicine to delete.");
            return;
        }

        int medicineId = (int) jTable1.getValueAt(selectedRow, 0);

        Medicine medicineToRemove = Medicine.findMedicineById(medicineId);

        if (medicineToRemove != null) 
        {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this medicine?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) 
            {
                Medicine.removeMedicine(medicineId);
                refreshTable();
                javax.swing.JOptionPane.showMessageDialog(this, "Medicine deleted successfully!");
            }
        } 
        else 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected medicine not found.");
        }
    }//GEN-LAST:event_DeleteMedicineActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new AdminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void MedicineQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineQuantityActionPerformed

    private void MedicineIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineIDActionPerformed

    private void MedicineNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineNameActionPerformed

    private void MedicineBatchNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineBatchNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineBatchNumberActionPerformed

    private void MedicinePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicinePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicinePriceActionPerformed

    private void MedicineExpiryDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineExpiryDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineExpiryDateActionPerformed

    private void refreshTable() 
    {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Medicine medicine : Medicine.getAllMedicines()) 
        {
            model.addRow(new Object[]{medicine.getId(), medicine.getName(), medicine.getBatchNo(), medicine.getPrice(), medicine.getQuantity(), medicine.getExpiryDate()});
        }
    }
    
    private void clearFields() 
    {
        MedicineID.setForeground(Color.GRAY);
        MedicineID.setText("Enter medicine ID");

        MedicineName.setForeground(Color.GRAY);
        MedicineName.setText("Enter name");

        MedicineBatchNumber.setForeground(Color.GRAY);
        MedicineBatchNumber.setText("Enter batch number");

        MedicinePrice.setForeground(Color.GRAY);
        MedicinePrice.setText("Enter price");

        MedicineQuantity.setForeground(Color.GRAY);
        MedicineQuantity.setText("Enter quantity");

        MedicineExpiryDate.setForeground(Color.GRAY);
        MedicineExpiryDate.setText("Enter expiry date (YYYY-MM-DD)");
    }
    
    private void setupPlaceholder(JTextField textField, String placeholder) 
    {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        textField.setForeground(Color.GRAY);
        textField.setFont(fontUsed);
        textField.setText(placeholder);

        textField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().equals(placeholder)) 
                {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                    textField.setFont(fontUsed);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().isEmpty()) 
                {
                    textField.setForeground(Color.GRAY);
                    textField.setFont(fontUsed);
                    textField.setText(placeholder);
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(ManageMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(ManageMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(ManageMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(ManageMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ManageMedicines().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMedicine;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JButton DeleteMedicine;
    private javax.swing.JLabel ManageMedicinesTitle;
    private javax.swing.JTextField MedicineBatchNumber;
    private javax.swing.JTextField MedicineExpiryDate;
    private javax.swing.JTextField MedicineID;
    private javax.swing.JTextField MedicineName;
    private javax.swing.JTextField MedicinePrice;
    private javax.swing.JTextField MedicineQuantity;
    private javax.swing.JButton UpdateMedicine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
