/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class ManageAdmins extends javax.swing.JFrame {

    /**
     * Creates new form ManageAdmins
     */
    public ManageAdmins()
    {
        initComponents();
        
        //Set up placeholders for all text fields
        setupPlaceholder(AdminID, "Enter admin ID");
        setupPlaceholder(AdminName, "Enter full name");
        setupPlaceholder(AdminUsername, "Enter username");
        setupPlaceholder(AdminEmail, "Enter email");
        setupPlaceholder(AdminPhone, "Enter phone number");
        setupPasswordPlaceholder(AdminPassword, "Enter password");
        
        // Window size + its place 
        this.setSize(950, 630);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.NORMAL);
        
        refreshTable();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Background = new javax.swing.JPanel();
        DeleteAdmin = new javax.swing.JButton();
        AddAdmin1 = new javax.swing.JButton();
        AdminPhone = new javax.swing.JTextField();
        AdminEmail = new javax.swing.JTextField();
        AdminUsername = new javax.swing.JTextField();
        AdminName = new javax.swing.JTextField();
        AdminID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ManageAdminsTitle = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        AdminPassword = new javax.swing.JPasswordField();
        AdminShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));

        Background.setBackground(new java.awt.Color(37, 95, 214));
        Background.setForeground(new java.awt.Color(37, 95, 214));
        Background.setLayout(new java.awt.GridBagLayout());

        DeleteAdmin.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        DeleteAdmin.setForeground(new java.awt.Color(37, 95, 214));
        DeleteAdmin.setText("Delete Admin");
        DeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 20, 0, 0);
        Background.add(DeleteAdmin, gridBagConstraints);

        AddAdmin1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        AddAdmin1.setForeground(new java.awt.Color(37, 95, 214));
        AddAdmin1.setText("Add Admin");
        AddAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdmin1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 50, 0, 0);
        Background.add(AddAdmin1, gridBagConstraints);

        AdminPhone.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminPhone.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminPhone.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminPhone.setPreferredSize(new java.awt.Dimension(100, 30));
        AdminPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPhoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 0, 0);
        Background.add(AdminPhone, gridBagConstraints);

        AdminEmail.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminEmail.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminEmail.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminEmail.setPreferredSize(new java.awt.Dimension(100, 30));
        AdminEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminEmailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 0, 0);
        Background.add(AdminEmail, gridBagConstraints);

        AdminUsername.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminUsername.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminUsername.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminUsername.setPreferredSize(new java.awt.Dimension(100, 30));
        AdminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 0, 0);
        Background.add(AdminUsername, gridBagConstraints);

        AdminName.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminName.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminName.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminName.setPreferredSize(new java.awt.Dimension(100, 30));
        AdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 0, 0);
        Background.add(AdminName, gridBagConstraints);

        AdminID.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminID.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminID.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminID.setPreferredSize(new java.awt.Dimension(100, 30));
        AdminID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(121, 15, 0, 0);
        Background.add(AdminID, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Username", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 454;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 42, 35, 45);
        Background.add(jScrollPane1, gridBagConstraints);

        ManageAdminsTitle.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        ManageAdminsTitle.setForeground(new java.awt.Color(255, 255, 255));
        ManageAdminsTitle.setText("Manage Admins");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 41, 0, 0);
        Background.add(ManageAdminsTitle, gridBagConstraints);

        BackButton.setForeground(new java.awt.Color(37, 95, 214));
        BackButton.setText("<-");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 50, 0, 0);
        Background.add(BackButton, gridBagConstraints);

        AdminPassword.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        AdminPassword.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        AdminPassword.setMinimumSize(new java.awt.Dimension(100, 30));
        AdminPassword.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 0, 0);
        Background.add(AdminPassword, gridBagConstraints);

        AdminShowPassword.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        AdminShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        AdminShowPassword.setText("Show Password");
        AdminShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminShowPasswordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        Background.add(AdminShowPassword, gridBagConstraints);

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAdminActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1)
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an admin to delete.");
            return;
        }

        String adminId = jTable1.getValueAt(selectedRow, 0).toString();

        Admin adminToRemove = null;
        for (Admin admin : Admin.getAdmins())
        {
            if (admin.getId().equals(adminId))
            {
                adminToRemove = admin;
                break;
            }
        }

        if (adminToRemove != null)
        {
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this admin?", "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                Admin.removeAdmin(adminToRemove);
                refreshTable();
                javax.swing.JOptionPane.showMessageDialog(this, "Admin deleted successfully!");
            }
        } 
        else
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Selected admin not found.");
        }
    }//GEN-LAST:event_DeleteAdminActionPerformed

    private void AddAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdmin1ActionPerformed
        String id = AdminID.getText().trim();
        String name = AdminName.getText().trim();
        String username = AdminUsername.getText().trim();
        String email = AdminEmail.getText().trim();
        String phone = AdminPhone.getText().trim();
        String password = AdminPassword.getText().trim(); 

        // Check if any field still contains placeholder text
        if (id.equals("Enter admin ID") || name.equals("Enter full name") || username.equals("Enter username") || email.equals("Enter email") || phone.equals("Enter phone number") || password.equals("Enter password"))
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        // input Validation
        if (id.isEmpty() || name.isEmpty() || username.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty())
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid email format.");
            return;
        }

        if (!phone.matches("\\d+")) 
        {
            javax.swing.JOptionPane.showMessageDialog(this, "Phone number must contain digits only.");
            return;
        }

        // Check if username is already taken
        for (Admin admin : Admin.getAdmins()) 
        {
            if (admin.getUsername().equals(username)) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, "Username already exists. Please choose another.");
                return;
            }
        }

        Admin newAdmin = new Admin(id, name, username, email, phone, password);
        Admin.addAdmin(newAdmin);

        refreshTable();
        clearFields();

        javax.swing.JOptionPane.showMessageDialog(this, "Admin added successfully!");
    }//GEN-LAST:event_AddAdmin1ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new AdminHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void AdminPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminPhoneActionPerformed

    private void AdminIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminIDActionPerformed

    private void AdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminNameActionPerformed

    private void AdminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminUsernameActionPerformed

    private void AdminEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminEmailActionPerformed

    private void AdminShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminShowPasswordActionPerformed
        if (String.valueOf(AdminPassword.getPassword()).equals("Enter password")) {
        return; // If it is the password placeholder, return and change nothing.
        }
        
        if (AdminShowPassword.isSelected())
        {
            AdminPassword.setEchoChar((char)0);
        }
        else
        {
            AdminPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_AdminShowPasswordActionPerformed
    
    private void refreshTable() 
    {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Admin admin : Admin.getAdmins()) 
        {
            Object[] row = {admin.getId(), admin.getName(), admin.getUsername(), admin.getEmail(), admin.getPhone(), admin.getPassword()};
            model.addRow(row);
        }
    }
    
    private void clearFields() 
    {
        AdminID.setForeground(Color.GRAY);
        AdminID.setText("Enter admin ID");

        AdminName.setForeground(Color.GRAY);
        AdminName.setText("Enter full name");

        AdminUsername.setForeground(Color.GRAY);
        AdminUsername.setText("Enter username");

        AdminEmail.setForeground(Color.GRAY);
        AdminEmail.setText("Enter email");

        AdminPhone.setForeground(Color.GRAY);
        AdminPhone.setText("Enter phone number");

        AdminPassword.setForeground(Color.GRAY);
        AdminPassword.setEchoChar((char)0);
        AdminPassword.setText("Enter password");
    }
    
    private void setupPlaceholder(JTextField textField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        textField.setForeground(Color.GRAY);
        textField.setFont(fontUsed);
        textField.setText(placeholder);

        textField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().equals(placeholder)) 
                {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                    textField.setFont(fontUsed);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (textField.getText().isEmpty()) 
                {
                    textField.setForeground(Color.GRAY);
                    textField.setFont(fontUsed);
                    textField.setText(placeholder);
                }
            }
        });
    }
    
    private void setupPasswordPlaceholder(JPasswordField passwordField, String placeholder) {
        Font fontUsed = new Font("Gadugi", Font.BOLD, 14);

        passwordField.setForeground(Color.GRAY);
        passwordField.setFont(fontUsed);
        passwordField.setEchoChar((char)0); // Show actual text instead of '*'
        passwordField.setText(placeholder);

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() 
        {
            public void focusGained(java.awt.event.FocusEvent evt) 
            {
                if (String.valueOf(passwordField.getPassword()).equals(placeholder)) 
                {
                    passwordField.setText("");
                    passwordField.setForeground(Color.BLACK);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar('*'); // Switch back to '*' when typing
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) 
            {
                if (passwordField.getPassword().length == 0) 
                {
                    passwordField.setForeground(Color.GRAY);
                    passwordField.setFont(fontUsed);
                    passwordField.setEchoChar((char)0); // Show actual text again
                    passwordField.setText(placeholder);
                }
            }
        }
        );
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAdmins().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdmin1;
    private javax.swing.JTextField AdminEmail;
    private javax.swing.JTextField AdminID;
    private javax.swing.JTextField AdminName;
    private javax.swing.JPasswordField AdminPassword;
    private javax.swing.JTextField AdminPhone;
    private javax.swing.JCheckBox AdminShowPassword;
    private javax.swing.JTextField AdminUsername;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JButton DeleteAdmin;
    private javax.swing.JLabel ManageAdminsTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
