/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author Mohamed
 */
public class ViewChats_Interface extends javax.swing.JFrame {

    /**
     * Creates new form ViewChats_Interface
     */
    
    public ViewChats_Interface() {
        initComponents();
        

        if(SessionController.getCurrentUser() instanceof Client)
            loadDoctors();
        else
            loadClients();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 51));
        setIconImages(null);
        setLocationByPlatform(true);
        setName("ViewChats"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(34, 40, 49));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(34, 40, 49));
        jTextField1.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(223, 208, 184));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Chats");
        jTextField1.setActionCommand("null");
        jTextField1.setBorder(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setBackground(new java.awt.Color(57, 62, 70));
        jList1.setBorder(null);
        jList1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jList1.setForeground(new java.awt.Color(223, 208, 184));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.setFixedCellHeight(60);
        jList1.setSelectionBackground(new java.awt.Color(148, 137, 121));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setBackground(new java.awt.Color(34, 40, 49));
        jButton1.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(223, 208, 184));
        jButton1.setText("Open Chat");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(223, 208, 184)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(34, 40, 49));
        jButton2.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(223, 208, 184));
        jButton2.setText("Delete Chat");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(223, 208, 184)));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(34, 40, 49));
        jButton3.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(223, 208, 184));
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(223, 208, 184)));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        int index =jList1.getSelectedIndex();
        if(index ==-1)
            index = 0;
        jButton1.setEnabled(true);
        jButton1.setOpaque(true);
        jButton2.setEnabled(false);
        jButton2.setOpaque(false);
        //Enables the delete button only if a chat already exists. Used in the case of a client.
        if(SessionController.getCurrentUser() instanceof Client){
            for(Chat a: Chat.getUserChats())
            {
                Doctor temp = Doctor.getDoctors().get(index);
                temp.getId();
                if(a.getDoctorID().equals(temp.getId())){
                    jButton2.setEnabled(true);
                    jButton2.setOpaque(true);
                    return;
                }
            }
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Chat_Interface next = new Chat_Interface(returnCurrentChat());
            next.setSize(getSize());
            next.setLocation(getLocation());
            next.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(57, 62, 70));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(34, 40, 49));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground(new Color(57, 62, 70));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(new Color(34, 40, 49));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(showConfirmDialog()){
            Chat.deleteChat(returnCurrentChat());
        }
        if(SessionController.getCurrentUser() instanceof Client)
            loadDoctors();
        else
            loadClients();
        jButton1.setEnabled(false);
        jButton1.setOpaque(false);
        jButton2.setEnabled(false);
        jButton2.setOpaque(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(new Color(57, 62, 70));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(new Color(34, 40, 49));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(SessionController.getCurrentUser() instanceof Client){
            ClientHome next = new ClientHome();
            next.setSize(getSize());
            next.setLocation(getLocation());
            next.setVisible(true);
            dispose();
        }
        else{
            DoctorHome_Interface next = new DoctorHome_Interface();
            next.setSize(getSize());
            next.setLocation(getLocation());
            next.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private Chat returnCurrentChat(){
        int index =jList1.getSelectedIndex();
        Chat chat;
        if(SessionController.getCurrentUser() instanceof Client){
            for(Chat a: Chat.getUserChats())
            {
                Doctor temp = Doctor.getDoctors().get(index);
                temp.getId();
                if(a.getDoctorID().equals(temp.getId())){
                    System.out.println("Finding Doctors");
                    chat = a;
                    return(Chat.getUserChats().get(index));
                }
            }
            return new Chat((Doctor.getDoctors().get(index).getId()));
        }
    System.out.println("Finding Clients");
    return(Chat.getUserChats().get(index));
}
    
    public boolean showConfirmDialog() {
    int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this chat?", "Confirm Chat Delete", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
    return (result == JOptionPane.OK_OPTION);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChats_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChats_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChats_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChats_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SessionController.signUpClient("C001", "Ramy EmadEldin", "RamyE", "ramy55@gmail.com", "01223572404", "ramy55", "Elnozha");
                SessionController.loginUser("ramy55@gmail.com", "ramy55", "Client");
                Doctor D1 = new Doctor("General Practitioner","EG-123456",150.5f,"D001","Mostafa Omar","Dr.Mostafa","mostafa@hootmail.com","01099999999","A123#uMa984Hj"); // created a new doctor object
                Doctor.addDoctor(D1);// adding the new doctor object (D1) using the method addDoctor()
                Doctor D2 = new Doctor("Internal Medicine","EG-654321",250.5f,"D002","Mohammed Khaled","Dr.Mohammed24","Mohammed24@gmail.com","01012345678","H%67328%%Ahbcfmnss"); // created a new doctor object
                Doctor.addDoctor(D2); // adding the new doctor object (D2) using the method addDoctor()
                Doctor D3 = new Doctor("Neurosurgery","EG-644321",220.5f,"D003","Ramy Emad","Ramroom","Ramroom@gmail.com","01012345678","H%673342cfmnss"); // created a new doctor object
                Doctor.addDoctor(D3); // adding the new doctor object (D2) using the method addDoctor()
                Doctor D4 = new Doctor("Heartsurgeon","EG-625321",210.5f,"D004","Youssef Hazem","Youssef Hazem","Youssef Hazem@gmail.com","01012345678","Hdasfsdhbcfmnss"); // created a new doctor object
                Doctor.addDoctor(D4); // adding the new doctor object (D2) using the method addDoctor()
                Chat a1 = new Chat("D001");
                a1.sendMessage("Good morning, Doctor");
                a1.sendMessage("I have some back pain.");
                Chat a2 = new Chat("D002");
                a2.sendMessage("Good afternoon, I have head pain.");
                SessionController.logoutUser();
                SessionController.loginUser("mostafa@hootmail.com", "A123#uMa984Hj", "Doctor");
                a1.sendMessage("Come to my office for a checkup.");
                new ViewChats_Interface().setVisible(true);
            }
        });
    }
    private void loadDoctors(){
        ArrayList<Doctor> doctorList = Doctor.getDoctors();
        String[] doctors = new String[doctorList.size()];
        System.out.println("Here");
        for (int i = 0; i<doctorList.size();i++)
        {
            doctors[i] = "" + doctorList.get(i).getName()+" - "+ doctorList.get(i).getSpecialization();
            while(doctors[i].length()<48){
                doctors[i]+= " ";
            }
            boolean hasChat = false;
            //Checks if user has a chat with said Doctor
            for(Chat b: Chat.getUserChats()){

                if(doctorList.get(i).getId().equals(b.getDoctorID())){
                    hasChat = true;
                }
            }
            if(hasChat){
                doctors[i]+= " |Continue chat|";
            }
            else{
                doctors[i]+= "|Start New Chat|";
            }
        }
        jList1.setListData(doctors);
    }
    
    private void loadClients(){
        String[] Clients = new String[Chat.getUserChats().size()];
        for(int i = 0;i<Chat.getUserChats().size();i++){
            for(Client a: Client.getClients()){
                Chat b = Chat.getUserChats().get(i);
                if(b.getClientID().equals(a.getId()))
                {
                    clients.add(a);
                    Clients[i] = a.getName();
                    while(Clients[i].length()<48){
                        Clients[i]+= " ";
                    }
                    if(b.getMessages().get(b.getMessages().size()-1).getSenderID().equals(SessionController.getCurrentUser().getId())){
                        Clients[i]+= "|View chat|";
                    }
                    else{
                        Clients[i]+= "|Reply to Client|";
                    }
                }
            }
        }
        jList1.setListData(Clients);
    }
    private ArrayList<Client> clients = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}